version: '3.3'

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: gpteleg_bot
    env_file: 
      - .env
    depends_on:  
      - db

  db:
    image: postgres:12-alpine
    volumes:  
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  
  admin:
    build: 
     context: ./admin_panel
     dockerfile: Dockerfile   
    image: admin_panel
    ports:
     - "5000:5000"
    depends_on:
      - db

volumes:
  db: